let suggestions = [
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "123, azikoro road,Lagos",
    "13 kudirat road, lagos",
    "13 kudirat road, lagos",
    "13 kudirat road, lagos",
    "13 kudirat road, lagos",
    "13 kudirat road, lagos",
    "13 kudirat road, lagos",
    "13 kudirat road, lagos",
    "danny obito"
]